"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Activity, ExternalLink, FileText, ImageIcon, LayoutDashboard, LogOut, Pencil, Pin, Save, Settings, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast, Toaster } from "sonner";
import type { Post } from "../lib/content";

type Data={settings:Record<string,string|null>;stats:Array<{key:string;label_ko:string;label_en:string;value:string;sort_order:number}>;posts:Post[]};
export default function AdminDashboard({user,signOutPath}:{user:{displayName:string;email:string};signOutPath:string}){
 const [data,setData]=useState<Data|null>(null);const [editing,setEditing]=useState<Post|null>(null);const [busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch("/api/admin/content");if(r.ok)setData(await r.json());else toast.error("관리 데이터를 불러오지 못했습니다.")};
 // Initial data loading is intentionally tied to the client mount.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{load()},[]);
 const submit=async(url:string,body:FormData|unknown,method="POST")=>{setBusy(true);const r=await fetch(url,{method,body:body instanceof FormData?body:JSON.stringify(body),headers:body instanceof FormData?undefined:{"content-type":"application/json"}});const j=await r.json();setBusy(false);if(!r.ok){toast.error(j.error||"저장하지 못했습니다.");return false}toast.success("저장했습니다.");await load();return true};
 if(!data)return <div className="grid min-h-screen place-items-center bg-slate-50 text-[#092a52]">관리자 화면을 불러오는 중입니다.</div>;
 const s=data.settings;
 return <div className="min-h-screen bg-[#f4f7fa] text-[#102a43]"><Toaster richColors/>
  <aside className="fixed inset-y-0 left-0 hidden w-64 bg-[#071f35] p-6 text-white lg:block"><Link href="/" className="text-xl font-bold">◎ LINKIMPACT</Link><p className="mt-2 text-xs text-slate-400">Content Management</p><nav className="mt-12 space-y-2 text-sm"><a href="#dashboard" className="flex gap-3 rounded-lg bg-white/10 px-4 py-3"><LayoutDashboard size={18}/> 대시보드</a><a href="#pages" className="flex gap-3 px-4 py-3 text-slate-300"><Settings size={18}/> 메인 페이지</a><a href="#posts" className="flex gap-3 px-4 py-3 text-slate-300"><FileText size={18}/> 게시글 관리</a><a href="#media" className="flex gap-3 px-4 py-3 text-slate-300"><ImageIcon size={18}/> 이미지 관리</a></nav></aside>
  <main className="lg:ml-64"><header className="sticky top-0 z-20 flex h-20 items-center justify-between border-b bg-white px-5 md:px-10"><div><h1 className="text-xl font-bold">관리자 대시보드</h1><p className="text-xs text-slate-500">{user.displayName}</p></div><div className="flex gap-2"><Button variant="outline" asChild><Link href="/" target="_blank">사이트 보기 <ExternalLink/></Link></Button><Button variant="ghost" asChild><a href={signOutPath}><LogOut/> 로그아웃</a></Button></div></header>
   <div className="mx-auto max-w-6xl p-5 md:p-10" id="dashboard"><div className="grid gap-4 sm:grid-cols-3"><Card label="전체 게시글" value={String(data.posts.length)} icon={<FileText/>}/><Card label="게시된 글" value={String(data.posts.filter(p=>p.status==="published").length)} icon={<Activity/>}/><Card label="임시저장" value={String(data.posts.filter(p=>p.status==="draft").length)} icon={<Pencil/>}/></div>
    <Tabs defaultValue="pages" className="mt-8"><TabsList className="h-auto w-full justify-start bg-white p-2"><TabsTrigger value="pages" className="px-5 py-3">메인 페이지 관리</TabsTrigger><TabsTrigger value="posts" className="px-5 py-3">게시글 관리</TabsTrigger><TabsTrigger value="stats" className="px-5 py-3">성과 수치</TabsTrigger></TabsList>
     <TabsContent value="pages" id="pages"><form className="mt-5 space-y-6" onSubmit={async e=>{e.preventDefault();await submit("/api/admin/settings",new FormData(e.currentTarget))}}><input type="hidden" name="current_image_key" value={s.hero_image_key||""}/><Section title="히어로 영역" description="홈페이지 첫 화면의 문구와 배경을 수정합니다."><div className="grid gap-5 md:grid-cols-2">{prefilled("hero_title_ko","메인 제목 (한글)",s,true)}{prefilled("hero_title_en","메인 제목 (영문)",s,true)}{prefilled("hero_lead_ko","보조 문구 (한글)",s)}{prefilled("hero_lead_en","보조 문구 (영문)",s)}{prefilled("hero_body_ko","소개 문구 (한글)",s,true)}{prefilled("hero_body_en","소개 문구 (영문)",s,true)}</div><label className="mt-5 block rounded-xl border border-dashed p-5"><span className="mb-2 block text-sm font-semibold">배경 이미지 교체</span><Input name="hero_image" type="file" accept="image/*"/><small className="mt-2 block text-slate-500">JPG·PNG·WEBP, 최대 10MB. 미선택 시 기존 이미지가 유지됩니다.</small></label></Section><Section title="미션"><div className="grid gap-5 md:grid-cols-2">{prefilled("mission_title_ko","제목 (한글)",s,true)}{prefilled("mission_title_en","제목 (영문)",s,true)}{prefilled("mission_body_ko","본문 (한글)",s,true)}{prefilled("mission_body_en","본문 (영문)",s,true)}</div></Section><Section title="NatureLens"><div className="grid gap-5 md:grid-cols-2">{prefilled("platform_title_ko","제목 (한글)",s,true)}{prefilled("platform_title_en","제목 (영문)",s,true)}{prefilled("platform_body_ko","본문 (한글)",s,true)}{prefilled("platform_body_en","본문 (영문)",s,true)}</div></Section><Section title="비전 및 후원"><div className="grid gap-5 md:grid-cols-2">{prefilled("vision_title_ko","제목 (한글)",s,true)}{prefilled("vision_title_en","제목 (영문)",s,true)}{prefilled("vision_body_ko","본문 (한글)",s,true)}{prefilled("vision_body_en","본문 (영문)",s,true)}{prefilled("donate_url","후원 버튼 연결 주소",s)}</div></Section><div className="sticky bottom-5 flex justify-end"><Button size="lg" disabled={busy}><Save/> {busy?"저장 중":"변경사항 게시"}</Button></div></form></TabsContent>
     <TabsContent value="posts" id="posts"><div className="mt-5 grid gap-6 xl:grid-cols-[1fr_1.2fr]"><PostForm post={editing} busy={busy} onSaved={async(fd)=>{const ok=await submit(editing?`/api/admin/posts/${editing.id}`:"/api/admin/posts",fd,editing?"PUT":"POST");if(ok)setEditing(null)}} onCancel={()=>setEditing(null)}/><Section title="게시글 목록" description="수정하거나 삭제할 게시글을 선택하세요."><div className="space-y-3">{data.posts.map(p=><div key={p.id} className="flex items-center gap-3 rounded-xl border p-4"><div className="min-w-0 flex-1"><div className="flex gap-2"><span className="text-xs font-bold text-[#287d44]">{p.type==="notice"?"공지":"활동"}</span>{p.is_pinned?<Pin size={13}/>:null}<span className="text-xs text-slate-400">{p.status==="published"?"게시":"임시저장"}</span></div><p className="truncate font-semibold">{p.title_ko}</p></div><Button size="icon" variant="ghost" onClick={()=>setEditing(p)}><Pencil/></Button><Button size="icon" variant="ghost" className="text-red-600" onClick={async()=>{if(confirm("이 게시글을 삭제할까요?"))await submit(`/api/admin/posts/${p.id}`,{}, "DELETE")}}><Trash2/></Button></div>)}{data.posts.length===0?<p className="py-10 text-center text-sm text-slate-500">아직 등록된 게시글이 없습니다.</p>:null}</div></Section></div></TabsContent>
     <TabsContent value="stats"><Section title="성과 수치 관리" description="메인 페이지 OUR IMPACT 영역에 표시됩니다."><form onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const items=data.stats.map((x,i)=>({...x,label_ko:String(fd.get(`ko_${i}`)),label_en:String(fd.get(`en_${i}`)),value:String(fd.get(`value_${i}`))}));await submit("/api/admin/stats",items)}} className="space-y-4">{data.stats.map((x,i)=><div key={x.key} className="grid gap-3 rounded-xl border p-4 md:grid-cols-3"><Input name={`ko_${i}`} defaultValue={x.label_ko}/><Input name={`en_${i}`} defaultValue={x.label_en}/><Input name={`value_${i}`} defaultValue={x.value}/></div>)}<Button disabled={busy}><Save/> 수치 저장</Button></form></Section></TabsContent>
    </Tabs>
   </div>
  </main>
 </div>
}

function Card({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="flex items-center gap-4 rounded-2xl bg-white p-6 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-xl bg-blue-50 text-[#0b4a7d]">{icon}</span><div><span className="text-sm text-slate-500">{label}</span><strong className="block text-3xl">{value}</strong></div></div>}
function Section({title,description,children}:{title:string;description?:string;children:React.ReactNode}){return <section className="rounded-2xl bg-white p-6 shadow-sm md:p-8"><h2 className="text-xl font-bold">{title}</h2>{description?<p className="mt-1 text-sm text-slate-500">{description}</p>:null}<div className="mt-6">{children}</div></section>}
function prefilled(name:string,label:string,s:Record<string,string|null>,multi=false){return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span>{multi?<Textarea name={name} rows={3} defaultValue={s[name]||""}/>:<Input name={name} defaultValue={s[name]||""}/>}</label>}
function PostForm({post,busy,onSaved,onCancel}:{post:Post|null;busy:boolean;onSaved:(f:FormData)=>void;onCancel:()=>void}){return <Section title={post?"게시글 수정":"새 게시글"} description="공지사항 또는 활동 소식을 작성합니다."><form key={post?.id||"new"} className="space-y-4" onSubmit={e=>{e.preventDefault();onSaved(new FormData(e.currentTarget))}}><input type="hidden" name="current_image_key" value={post?.image_key||""}/><div className="grid grid-cols-2 gap-3"><label><span className="mb-2 block text-sm font-semibold">유형</span><Select name="type" defaultValue={post?.type||"notice"}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="notice">공지사항</SelectItem><SelectItem value="activity">활동 소식</SelectItem></SelectContent></Select></label><label><span className="mb-2 block text-sm font-semibold">상태</span><Select name="status" defaultValue={post?.status||"draft"}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="draft">임시저장</SelectItem><SelectItem value="published">게시</SelectItem></SelectContent></Select></label></div><Input name="category" placeholder="카테고리" defaultValue={post?.category||"일반"}/><Input name="title_ko" required placeholder="제목 (한글)" defaultValue={post?.title_ko||""}/><Input name="title_en" placeholder="제목 (영문)" defaultValue={post?.title_en||""}/><Textarea name="excerpt_ko" placeholder="목록용 요약 (한글)" defaultValue={post?.excerpt_ko||""}/><Textarea name="excerpt_en" placeholder="목록용 요약 (영문)" defaultValue={post?.excerpt_en||""}/><Textarea name="content_ko" required rows={8} placeholder="본문 (한글)" defaultValue={post?.content_ko||""}/><Textarea name="content_en" rows={8} placeholder="본문 (영문)" defaultValue={post?.content_en||""}/><Input name="event_date" type="date" defaultValue={post?.event_date||""}/><Input name="image" type="file" accept="image/*"/><label className="flex items-center gap-3 text-sm"><Switch name="is_pinned" defaultChecked={Boolean(post?.is_pinned)}/> 중요 게시글 상단 고정</label><div className="flex gap-2"><Button disabled={busy}><Save/> {busy?"저장 중":"저장"}</Button>{post?<Button type="button" variant="outline" onClick={onCancel}>수정 취소</Button>:null}</div></form></Section>}
