"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, ArrowRight, Camera, Earth, Heart, Leaf, Menu, Network, Search, Share2, Sparkles, Users, X } from "lucide-react";
import type { Post } from "../lib/content";

type Settings=Record<string,string|null>;
const values=[[Users,"PEOPLE","시민과 커뮤니티 연결","모든 사람이 변화의 주체가 되는 참여 생태계 구축"],[Leaf,"PLANET","자연과 데이터 연결","자연을 관찰하고 데이터로 기록하여 지구를 더 깊이 이해"],[Sparkles,"TECHNOLOGY","기술과 행동 연결","AI와 디지털 기술로 더 나은 의사결정과 행동 지원"],[Earth,"LOCAL & GLOBAL","지역과 세계 연결","지역의 경험을 세계와 공유하고 글로벌 변화 네트워크 확장"],[Activity,"IMPACT","오늘과 미래 연결","지속가능한 임팩트를 설계하고 다음 세대를 위한 길 조성"]] as const;

function localDateKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}

export default function HomeClient({settings,posts,showAdmin,embedded=false}:{settings:Settings;posts:Post[];showAdmin:boolean;embedded?:boolean}){
 const [lang,setLang]=useState<"ko"|"en">("ko"); const [menu,setMenu]=useState(false); const [storyType,setStoryType]=useState<"notice"|"activity">("activity");
 const [popupOpen,setPopupOpen]=useState(false);
 const visiblePosts=useMemo(()=>posts.filter(post=>post.type===storyType).slice(0,storyType==="notice"?4:3),[posts,storyType]);
 const popupNotice=useMemo(()=>posts.find(post=>post.type==="notice"&&Boolean(post.is_pinned))||null,[posts]);
 useEffect(()=>{if(!popupNotice)return;const key=`linkimpact-notice-popup-${popupNotice.id}`;if(localStorage.getItem(key)!==localDateKey())setPopupOpen(true)},[popupNotice]);
 const hidePopupToday=()=>{if(popupNotice)localStorage.setItem(`linkimpact-notice-popup-${popupNotice.id}`,localDateKey());setPopupOpen(false)};
 const t=(key:string)=>settings[`${key}_${lang}`]||settings[`${key}_ko`]||"";
 const hero=settings.hero_image_key?`url("/api/media/${encodeURIComponent(settings.hero_image_key)}")`:'url("/assets/earth-network.png")';
 const popupImage=popupNotice?.image_key?(popupNotice.image_key.startsWith("/")?popupNotice.image_key:`/api/media/${encodeURIComponent(popupNotice.image_key)}`):"/assets/earth-network.png";
 return <div className="relative min-h-screen bg-white text-[#092a52]">
  {!embedded&&popupOpen&&popupNotice?<div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/55 p-4" role="dialog" aria-modal="true" aria-labelledby="notice-popup-title"><div className="relative w-full max-w-lg overflow-hidden rounded-3xl bg-white shadow-2xl"><button type="button" onClick={()=>setPopupOpen(false)} className="absolute right-4 top-4 z-10 grid h-10 w-10 place-items-center rounded-full bg-white/95 text-[#092a52] shadow" aria-label="공지 팝업 닫기"><X size={20}/></button><div className="aspect-[16/8] bg-slate-100 bg-cover bg-center" style={{backgroundImage:`url("${popupImage}")`}}/><div className="p-6 md:p-8"><span className="text-xs font-bold text-[#287d44]">NOTICE · {popupNotice.category}</span><h2 id="notice-popup-title" className="mt-3 text-2xl font-bold leading-tight">{lang==="ko"?popupNotice.title_ko:(popupNotice.title_en||popupNotice.title_ko)}</h2><p className="mt-4 text-sm leading-7 text-slate-600">{lang==="ko"?(popupNotice.excerpt_ko||popupNotice.content_ko):(popupNotice.excerpt_en||popupNotice.excerpt_ko||popupNotice.content_en||popupNotice.content_ko)}</p><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-5"><button type="button" onClick={hidePopupToday} className="text-sm font-semibold text-slate-500 hover:text-[#092a52]">오늘 하루 보지 않기</button><Link href={`/news/${popupNotice.id}`} onClick={()=>setPopupOpen(false)} className="inline-flex items-center gap-2 rounded-full bg-[#062c59] px-5 py-3 text-sm font-bold text-white">자세히 보기 <ArrowRight size={15}/></Link></div></div></div></div>:null}
  <header className="absolute inset-x-0 top-0 z-30"><div className="mx-auto flex h-20 max-w-[1180px] items-center justify-between px-5"><Link href="/" className="flex shrink-0 items-center gap-3" aria-label="LINKIMPACT 홈"><img src="/assets/linkimpact-logo.png" alt="LINKIMPACT 로고" className="h-9 w-auto object-contain md:h-11"/><span className="text-lg font-extrabold tracking-[-0.03em] text-[#092a52] md:text-xl">LINKIMPACT</span></Link><nav className={`${menu?"flex":"hidden"} absolute left-5 right-5 top-20 flex-col gap-5 rounded-2xl bg-white p-6 text-xs font-semibold shadow-xl md:static md:flex md:flex-row md:bg-transparent md:p-0 md:shadow-none`}><a href="#mission">ABOUT</a><a href="#work">OUR WORK</a><a href="#platform">PLATFORM</a><a href="#vision">PARTNERSHIP</a><Link href="/news">NEWS</Link></nav><div className="flex items-center gap-2"><button onClick={()=>setLang(lang==="ko"?"en":"ko")} className="rounded-full bg-white/80 px-4 py-3 text-xs font-bold">{lang==="ko"?"EN":"KO"}⌄</button><a href="https://together.kakao.com/fundraisings/139701/story" target="_blank" rel="noreferrer" className="hidden rounded-full bg-[#062c59] px-6 py-3 text-xs font-bold text-white sm:block">DONATE</a><button onClick={()=>setMenu(!menu)} className="p-2 md:hidden" aria-label="메뉴">{menu?<X/>:<Menu/>}</button></div></div></header>
  <section className="relative flex min-h-[700px] items-center bg-cover bg-center" style={{backgroundImage:`linear-gradient(90deg,rgba(249,247,240,.98) 0%,rgba(249,247,240,.78) 37%,rgba(249,247,240,0) 62%),${hero}`}}><div className="mx-auto w-full max-w-[1180px] px-5 pt-20"><div className="max-w-[650px]"><h1 className="whitespace-pre-line text-5xl font-bold leading-[.98] tracking-[-.06em] md:text-7xl">{t("hero_title")}</h1><p className="mt-7 text-lg font-semibold md:text-xl">{t("hero_lead")}</p><p className="mt-5 max-w-xl text-base leading-8">{t("hero_body")}</p><a href="#mission" className="mt-7 inline-flex items-center gap-8 rounded bg-[#062c59] px-6 py-4 text-xs font-bold text-white">OUR MISSION <ArrowRight size={16}/></a></div></div></section>
  <section id="mission" className="bg-[#fbfbfa] py-16"><div className="mx-auto grid max-w-[1180px] gap-10 px-5 lg:grid-cols-[1.6fr_repeat(5,1fr)]"><div><div className="text-xs font-bold">OUR MISSION</div><h2 className="mt-4 whitespace-pre-line text-3xl font-bold leading-tight">{t("mission_title")}</h2></div>{values.map(([Icon,title,sub,body])=><div key={title} className="border-t border-slate-200 pt-6 text-center lg:border-l lg:border-t-0 lg:px-5 lg:pt-0"><Icon className="mx-auto h-10 w-10 text-[#12629b]"/><h3 className="mt-4 text-sm font-bold">{title}</h3><strong className="mt-2 block text-sm">{sub}</strong><p className="mt-3 text-sm leading-6 text-slate-500">{body}</p></div>)}</div></section>
  <section id="platform" className="bg-[#043353] py-16 text-white"><div className="mx-auto grid max-w-[1180px] items-center gap-12 px-5 lg:grid-cols-[1fr_.8fr_1fr]"><div><div className="text-xs font-bold">OUR PLATFORM</div><h2 className="mt-3 text-4xl font-bold">NatureLens</h2><p className="mt-3 text-xl">{t("platform_title")}</p><p className="mt-5 leading-8 text-slate-200">{t("platform_body")}</p></div><a href="https://www.naturelens.kr" target="_blank" rel="noreferrer" aria-label="NatureLens 웹앱 열기" className="group relative mx-auto block h-80 w-44 rotate-[-5deg] overflow-hidden rounded-[2.2rem] border-[7px] border-slate-300 bg-white shadow-2xl transition hover:rotate-0 hover:scale-105"><iframe src="https://www.naturelens.kr" title="NatureLens 웹앱 모바일 화면" className="pointer-events-none h-[640px] w-[350px] origin-top-left scale-50 border-0" loading="lazy"/><span className="absolute inset-x-3 bottom-3 rounded-full bg-[#062c59]/95 px-3 py-2 text-center text-[11px] font-bold text-white shadow-lg">NatureLens 열기 ↗</span></a><div className="grid grid-cols-2 gap-7">{[{n:"327",l:lang==="ko"?"관찰 기록":"Records"},{n:"142",l:lang==="ko"?"발견 종":"Species found"},{n:"86",l:lang==="ko"?"참여자":"Contributors"},{n:"21",l:lang==="ko"?"탐사 경로":"Survey routes"}].map(x=><div key={x.l}><span className="text-xs">{x.l}</span><strong className="block text-3xl">{x.n}</strong></div>)}</div></div><div className="mx-auto mt-12 grid max-w-[1180px] grid-cols-3 gap-7 px-5 md:grid-cols-6">{[[Search,"OBSERVE"],[Camera,"RECORD"],[Sparkles,"ANALYZE"],[Earth,"MAP"],[Share2,"SHARE"],[ArrowRight,"ACT"]].map(([Icon,l])=><div key={l as string} className="text-center"><Icon className="mx-auto"/><strong className="mt-3 block text-xs">{l as string}</strong></div>)}</div></section>
  <section id="work" className="bg-slate-50 py-20"><div className="mx-auto max-w-[1180px] px-5"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-bold">LATEST STORIES</div><h2 className="mt-3 text-3xl font-bold">활동 소식과 공지사항</h2></div><Link href={`/news?type=${storyType}`} className="flex items-center gap-2 text-sm font-bold">전체 보기 <ArrowRight size={16}/></Link></div><div className="mt-8 inline-flex rounded-full bg-white p-1 shadow-sm" role="tablist" aria-label="소식 유형"><button role="tab" aria-selected={storyType==="activity"} onClick={()=>setStoryType("activity")} className={`rounded-full px-6 py-3 text-sm font-bold transition ${storyType==="activity"?"bg-[#062c59] text-white":"text-slate-500"}`}>활동 소식</button><button role="tab" aria-selected={storyType==="notice"} onClick={()=>setStoryType("notice")} className={`rounded-full px-6 py-3 text-sm font-bold transition ${storyType==="notice"?"bg-[#062c59] text-white":"text-slate-500"}`}>공지사항</button></div>{storyType==="notice"?<div className="mt-8 divide-y divide-slate-200 border-y border-slate-200 bg-white">{visiblePosts.map(p=><Link href={`/news/${p.id}`} key={p.id} className="group flex items-center gap-5 p-4 transition hover:bg-slate-50"><div className="h-20 w-28 shrink-0 rounded-lg bg-slate-200 bg-cover bg-center" style={{backgroundImage:`url("${p.image_key?(p.image_key.startsWith("/")?p.image_key:`/api/media/${encodeURIComponent(p.image_key)}`):"/assets/earth-network.png"}")`}}/><div className="min-w-0 flex-1"><span className="text-xs font-bold text-[#287d44]">{p.category}</span><h3 className="mt-1 truncate text-lg font-bold group-hover:underline">{lang==="ko"?p.title_ko:(p.title_en||p.title_ko)}</h3><p className="mt-1 truncate text-sm text-slate-500">{lang==="ko"?p.excerpt_ko:(p.excerpt_en||p.excerpt_ko)}</p></div><ArrowRight className="hidden shrink-0 sm:block" size={18}/></Link>)}</div>:<div className="mt-8 grid gap-6 md:grid-cols-3">{visiblePosts.map(p=><Link href={`/news/${p.id}`} key={p.id} className="group overflow-hidden rounded-2xl bg-white shadow-sm"><div className="aspect-[16/9] bg-slate-200 bg-cover bg-center" style={{backgroundImage:`url("${p.image_key?(p.image_key.startsWith("/")?p.image_key:`/api/media/${encodeURIComponent(p.image_key)}`):"/assets/earth-network.png"}")`}}/><div className="p-6"><span className="text-xs font-bold text-[#287d44]">{p.category}</span><h3 className="mt-3 text-xl font-bold group-hover:underline">{lang==="ko"?p.title_ko:(p.title_en||p.title_ko)}</h3><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-500">{lang==="ko"?p.excerpt_ko:(p.excerpt_en||p.excerpt_ko)}</p></div></Link>)}</div>}{visiblePosts.length===0&&<div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-slate-500">등록된 {storyType==="notice"?"공지사항":"활동 소식"}이 없습니다.</div>}</div></section>
  <section id="vision" className="bg-[linear-gradient(90deg,#031f3def,#052c59bd),url('/assets/earth-network.png')] bg-cover bg-center py-20 text-white"><div className="mx-auto grid max-w-[1180px] gap-14 px-5 lg:grid-cols-[1.1fr_1fr]"><div><div className="text-xs font-bold">OUR VISION</div><h2 className="mt-4 whitespace-pre-line text-3xl font-bold">{t("vision_title")}</h2><p className="mt-5 max-w-xl leading-8 text-slate-200">{t("vision_body")}</p></div><div className="grid grid-cols-2 gap-6 md:grid-cols-4">{[[Heart,"기부하기"],[Network,"파트너십"],[Users,"자원봉사"],[Sparkles,"캠페인 참여"]].map(([Icon,l])=><div key={l as string} className="text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full border border-white/40"><Icon/></span><strong className="mt-3 block text-sm">{l as string}</strong></div>)}</div></div></section>
  <footer className="bg-[#081f31] py-12 text-slate-300"><div className="mx-auto flex max-w-[1180px] flex-col justify-between gap-8 px-5 md:flex-row"><div className="font-bold text-white">◎ LINKIMPACT<small className="block text-[10px] font-normal">LINKED TO CHANGE THE WORLD</small></div><div className="flex flex-wrap gap-8 text-sm"><a href="#mission">ABOUT</a><a href="#work">OUR WORK</a><a href="#platform">PLATFORM</a><Link href="/news">NEWS</Link>{showAdmin?<Link href="/admin">ADMIN</Link>:null}</div><div className="text-xs">© 2026 LINKIMPACT.</div></div></footer>
 </div>;
}
