"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { ArrowLeft,Download,RefreshCw } from "lucide-react";

type Row={id:number;form_slug:string;lang:string;submitted_at:string;answers:Record<string,unknown>};

export default function FormSubmissionsClient({signOutPath}:{signOutPath:string}){
 const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const r=await fetch("/api/admin/forms/submissions");if(r.ok){const j=await r.json();setRows(j.submissions||[])}setLoading(false)};
 useEffect(()=>{load()},[]);
 const current=useMemo(()=>rows.filter(x=>x.form_slug==="wild-friends-2026"),[rows]);
 const csv=()=>{const head=["submitted_at","date","name","age","gender","phone","device","interests","message","lang"];const esc=(v:unknown)=>'"'+String(v??"").replaceAll('"','""')+'"';const lines=[head.join(","),...current.map(r=>{const a=r.answers;return [r.submitted_at,a.date,a.name,a.age,a.gender,a.phone,a.device,Array.isArray(a.interests)?a.interests.join(" | "):a.interests,a.message,r.lang].map(esc).join(",")})];const blob=new Blob(["\uFEFF"+lines.join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="wild-friends-2026-submissions.csv";a.click();URL.revokeObjectURL(url)};
 return <main className="min-h-screen bg-[#f4f7fa] text-[#102a43]"><header className="border-b bg-white px-5 py-5"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> 관리자 대시보드</Link><h1 className="mt-2 text-2xl font-black">신청 · 설문 관리</h1></div><a href={signOutPath} className="text-sm font-bold text-slate-500">로그아웃</a></div></header><div className="mx-auto max-w-7xl p-5 md:p-10"><div className="flex flex-wrap items-end justify-between gap-4 rounded-2xl bg-white p-6 shadow-sm"><div><p className="text-sm font-bold text-[#287d44]">야생 친구를 찾습니다</p><strong className="mt-1 block text-4xl">{current.length}</strong><span className="text-sm text-slate-500">접수된 신청</span></div><div className="flex gap-2"><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border px-4 py-3 text-sm font-bold"><RefreshCw size={16}/> 새로고침</button><button onClick={csv} disabled={!current.length} className="inline-flex items-center gap-2 rounded-xl bg-[#071f35] px-4 py-3 text-sm font-bold text-white disabled:opacity-40"><Download size={16}/> CSV 다운로드</button></div></div><div className="mt-6 overflow-hidden rounded-2xl bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["접수일","희망일","이름","연령","성별","연락처","기종","관심사","기대사항"].map(x=><th key={x} className="px-4 py-4">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={9} className="p-8 text-center text-slate-500">불러오는 중…</td></tr>:current.length?current.map(r=>{const a=r.answers;return <tr key={r.id} className="border-t align-top"><td className="whitespace-nowrap px-4 py-4">{new Date(r.submitted_at).toLocaleString("ko-KR")}</td><td className="whitespace-nowrap px-4 py-4">{String(a.date||"")}</td><td className="px-4 py-4 font-bold">{String(a.name||"")}</td><td className="px-4 py-4">{String(a.age||"")}</td><td className="px-4 py-4">{String(a.gender||"")}</td><td className="whitespace-nowrap px-4 py-4">{String(a.phone||"")}</td><td className="px-4 py-4">{String(a.device||"")}</td><td className="max-w-64 px-4 py-4">{Array.isArray(a.interests)?a.interests.join(", "):String(a.interests||"")}</td><td className="max-w-80 px-4 py-4">{String(a.message||"")}</td></tr>}):<tr><td colSpan={9} className="p-10 text-center text-slate-500">아직 접수된 신청이 없습니다.</td></tr>}</tbody></table></div></div><p className="mt-4 text-xs text-slate-500">이 화면과 응답 API는 LINKIMPACT 관리자 인증을 통과한 사용자만 접근할 수 있습니다.</p></div></main>
}
